### ISSUE TITLE
HU 03 Optimización de Horarios para Preparación de Exámenes Médicos

### ISSUE THREAD

**Issue by BenjaminPavez** [Zurickata/INF236-2023-2-GRUPO-10#4]
_Historia de usuario:_

Como personal médico, quiero revisar las horas asignadas del día para preparar de mejor manera los exámenes.

_Criterios de aceptación:_

Dado una tecnóloga/o médica conectada al sistema, cuando accedo a los horarios asignados del día, entonces el sistema debe mostrar de forma clara y organizada la lista de exámenes programados para ese día, incluyendo la hora, el tipo de examen y el paciente correspondiente.

**Comment by DiegoCisternas** [comment]
Ya completado
